### PR TITLE
Shell Brackets/Braces/Quotes only when necessary

### PR DESCRIPTION
**Pull request by grm34**
Signed-off-by: grm34 <jerem.pardo@tutanota.com>

### CODE REVIEW

**Comment by proffapt** [comment]
Someone will be using this on phone?
umm i saw all of the commits.. i was modifying the "" while expansion of the variables since it wasn't working with files containing spaces in their name.. which i discovered few minutes ago this pr.
Indentation is my nvim indentation setting i will fix it

All is good.. wanna ask about that banner.. or shall i implement it something like

```sh
# firls line
# blah blah
# another line
# end
```

**Review by grm34 — COMMENTED** [review]
Seems fine, sorry for indentation but was broked up in nvim (endline spaces and tabs)

**Comment by proffapt** [comment]
looks good then, can i edit this while merging?
i am not that experienced with github (the contribution and collaboration part).. so shall i merge and then edit or there is another way around this?

**Comment by grm34** [comment]
> Someone will be using this on phone? umm i saw all of the commits.. i was modifying the "" while expansion of the variables since it wasn't working with files containing spaces in their name.. which i discovered few minutes ago this pr. Indentation is my nvim indentation setting i will fix it
> 
> All is good.. wanna ask about that banner.. or shall i implement it something like
> 
> ```shell
> # firls line
> # blah blah
> # another line
> # end
> ```

Hmm yes, sorry for banner too (open it on phone term and see^^).
Lines of code should not be more than 78 length for better readability.

**Comment by proffapt** [comment]
for banner imma just remove "#" at the end part

**Pull request merged**
